### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by jagrg**

### CODE REVIEW

**Comment by ghost** [comment]
Hello,

I'm very sorry for the very long delay.  Thanks for contributing!

BTW, this project needs a new maintainer.  I currently don't use helm-bbdb.  Please tell me if you would be interested.  The main goal is probably to make the thing available again on Melpa and fix what people find then.

Some comments on your changes:
- factoring out the action list is a good idea.  The `:group` spec is redundant because it's the same as the default.  You can remove it.
- Deleting the window in `helm-bbdb-compose-mail`: instead of hardcoding the one or other preferrable behavior, I would like it better to factor out the function to start Email composing completely into a defcustom (e.g. `helm-bbdb-compose-mail-function`) and give it a reasonable default - maybe we can make use of the args of `compose-mail` in a clever way instead of calling `delete-window`?
- helm-bbdb-copy-mail-address: Giving a feedback with `message` would not be annoying and helpful I think.

Thanks!

Michael.

**Comment by jagrg** [comment]
Hi. Thanks for the feedback and don't worry about the delay. Regarding your proposal, I think I would rather improve my skills first before I can accept this. But thanks anyway.

I do use bbdb and I like helm, so helm-bbdb seems like a nice combination. If you don't mind me asking, what do you use now instead?

**Comment by ghost** [comment]
Jonathan Gregory notifications@github.com writes:

> Hi. Thanks for the feedback and don't worry about the delay. Regarding
> your proposal, I think I would rather improve my skills first before I
> can accept this. But thanks anyway.

I would still assist extensively.  But every contribution is welcome.

> I do use bbdb and I like helm, so helm-bbdb seems like a nice
> combination. If you don't mind me asking, what do you use now instead?

Just plain bbdb... Because I don't find what helm-bbdb offers is much
more convenient or useful than bbdb itself.  OTOH it currently even
limits the completion bbdb provides - with helm-bbdb, I can only match
against names.  bbdb also finds matches in the organization, for
example.

**Comment by ghost** [comment]
BTW, do you want to address some of my comments and add to your PR?

**Comment by jagrg** [comment]
I haven't addressed the second bullet. IMO the TO argument is sufficient for now. I find that the purpose of helm-bbdb is to eventually bypass the bbdb interface, so it seems reasonable to delete the bbdb window.

BTW, I've noticed that with the current code we cannot compose a message to multiple candidates.

**Comment by ghost** [comment]
Jonathan Gregory notifications@github.com writes:

> I haven't addressed the second bullet.

Thanks for addressing the others.

> IMO the TO argument is sufficient for now. I find that the purpose of
> helm-bbdb is to eventually bypass the bbdb interface, so it seems
> reasonable to delete the bbdb window.

Yes, but I think the bbdb buffer should not pop up at all.  Do you know
what is causing it to pop up?  I would rather fix the cause than to fix
the result afterwards.

> BTW, I've noticed that with the current code we cannot compose a
> message to multiple candidates.

Indeed.  Well, it should not be hard to do.  You can use
`helm-marked-candidates' to get the candidates, and use`mapconcat' or
so to combine them to a valid TO to hand over to `compose-message'.  Do
you want to give it a try?

BTW that's a thing which would benefit from a more sophisticated
matching implementation.

Thanks,

Michael.

**Comment by jagrg** [comment]
> > > > > On 14 Mar 2016 at 21:41, Michael Heerdegen notifications@github.com wrote:
> 
> Yes, but I think the bbdb buffer should not pop up at all. Do you
> know what is causing it to pop up? I would rather fix the cause than
> to fix the result afterwards.

I agree with you. The problem is that `helm-bbdb-get-record` uses `(bbdb
candidate nil)`, which opens a window by default. I don't think there's
an argument or variable that prevents this from happening.

> Indeed. Well, it should not be hard to do. You can use
> `helm-marked-candidates' to get the candidates, and use`mapconcat'
> or so to combine them to a valid TO to hand over to
> `compose-message'. Do you want to give it a try?

I can have a look at it when I find time.

> BTW that's a thing which would benefit from a more sophisticated
> matching implementation.

Yes. Maybe if we had name|email|phone columns it would look more like an
address book ;)

## 

Jonathan

**Comment by jagrg** [comment]
> Indeed. Well, it should not be hard to do. You can use `helm-marked-candidates' to get the candidates, and use`mapconcat' or so to combine them to a valid TO to hand over to `compose-message'. Do you want to give it a try?

I was able to hack my way around to achieve what you describe. I'm sure there's a better way of doing this. If you can improve the code, please do. I'd be curious to see.

``` elisp
(defun helm-bbdb-compose-mail (candidate)
  "Compose a mail with all records of bbdb buffer."
  (helm-bbdb-view-person-action candidate)
  (let ((address-str
         (mapconcat (lambda (x) (helm-bbdb-collect-mail x))
                    (helm-marked-candidates) ", ")))
    (delete-window)
    (compose-mail address-str)))

(defun helm-bbdb-collect-mail (string)
  (let ((list (bbdb-search (bbdb-records) string nil string nil nil)))
    (mapcar
     (lambda (record)
       (let ((mail (bbdb-mail-address record)))
     (mapcar
      (lambda (_)
        (setq result (format "%s" mail)))
      (bbdb-record-mail record))))
     list)
    (format result)))
```

**Comment by thierryvolpiatto** [comment]
IIRC with old bbdb the current `helm-bbdb-compose-mail` was composing a mail with one or more candidates that was previously concatenated in a bbdb buffer, isn't this the same actually ?
Anyway this should belong to another issue, so please open it.
For this pull request I think what @michael-heerdegen  said about `delete-window` is pertinent and should be applied, for the rest it seems correct (can't try it, as I don't use bbdb as addressbook).
So merging now, I will modify the delete-window issue afterward.

Thanks @jagrg and @michael-heerdegen

**Pull request merged**
